[package]
name = "dry_console_common"
edition = "2021"
version.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true

[dependencies]
ulid = { version = "1.1.3", features = ["serde"] }
sha2 = "0.10.8"
rand = "0.8.5"
