name: Enforce PR titles
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check_PR:
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: 'feat:,fix:,scope!,release:' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
